name: MGSurvE
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster
  - appdirs
  - babel
  - beautifulsoup4
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bs4
  - bzip2
  - c-ares
  - ca-certificates
  - cartopy
  - cffi
  - colorama
  - contourpy
  - cryptography
  - cycler
  - deap
  - et_xmlfile
  - fonttools
  - freetype
  - geos
  - idna
  - imagesize
  - importlib-metadata
  - jinja2
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - libjpeg-turbo
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libzlib
  - llvm-openmp
  - munkres
  - ncurses
  - numexpr
  - numpy
  - openjpeg
  - openpyxl
  - openssl
  - pillow
  - pip
  - pooch
  - proj
  - pthread-stubs
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - readline
  - setuptools
  - shapely
  - six
  - snowballstemmer
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - tk
  - unicodedata2
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zipp
  - zlib
  - zstd
  - pip:
      - anyio
      - appnope
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - asttokens
      - attrs
      - backcall
      - bleach
      - certifi
      - chardet
      - charset-normalizer
      - click
      - click-plugins
      - cligj
      - comm
      - compress-pickle
      - debugpy
      - decorator
      - defusedxml
      - dill
      - docutils
      - executing
      - fastjsonschema
      - fiona
      - fqdn
      - geojson
      - geopandas
      - haversine
      - ipykernel
      - ipython
      - ipython-genutils
      - ipywidgets
      - isoduration
      - jaraco-classes
      - jedi
      - joblib
      - jsonpointer
      - jsonschema
      - jupyter
      - jupyter-client
      - jupyter-console
      - jupyter-core
      - jupyter-events
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab-pygments
      - jupyterlab-widgets
      - keyring
      - libpysal
      - lxml
      - markdown-it-py
      - markupsafe
      - matplotlib
      - matplotlib-inline
      - mdurl
      - mgsurve
      - mistune
      - more-itertools
      - mpmath
      - munch
      - nbclassic
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - networkx
      - notebook
      - notebook-shim
      - osmpythontools
      - packaging
      - pandas
      - pandocfilters
      - parso
      - pexpect
      - pickleshare
      - pkginfo
      - platformdirs
      - pointpats
      - prometheus-client
      - prompt-toolkit
      - psutil
      - ptyprocess
      - pure-eval
      - pyrsistent
      - python-json-logger
      - pytz
      - pyyaml
      - pyzmq
      - qtconsole
      - qtpy
      - readme-renderer
      - requests
      - requests-toolbelt
      - rfc3339-validator
      - rfc3986
      - rfc3986-validator
      - rich
      - scikit-learn
      - scipy
      - send2trash
      - sniffio
      - soupsieve
      - sphinx
      - sphinx-rtd-theme
      - sphinxcontrib-jquery
      - stack-data
      - sympy
      - terminado
      - threadpoolctl
      - tinycss2
      - tornado
      - traitlets
      - twine
      - tzdata
      - ujson
      - uri-template
      - urllib3
      - vincenty
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - widgetsnbextension
      - xarray
