name: MGSurvE
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - appdirs
  - beautifulsoup4
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cartopy
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cycler
  - deap
  - fonttools
  - freetype
  - geos
  - giflib
  - idna
  - jinja2
  - jpeg
  - keyutils
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - liblapack
  - libnghttp2
  - libnsl
  - libopenblas
  - libpng
  - libpysal
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libzlib
  - lz4-c
  - markupsafe
  - matplotlib-base
  - munkres
  - ncurses
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - proj
  - pthread-stubs
  - pycparser
  - pyopenssl
  - pyparsing
  - pyproj
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - requests
  - scipy
  - setuptools
  - shapely
  - six
  - soupsieve
  - sqlite
  - tk
  - tzdata
  - unicodedata2
  - urllib3
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zlib
  - zstd
  - pip:
      - alabaster
      - babel
      - bleach
      - click
      - click-plugins
      - cligj
      - commonmark
      - dill
      - docutils
      - fiona
      - geopandas
      - haversine
      - imagesize
      - importlib-metadata
      - ipykernel
      - jeepney
      - keyring
      - mgsurve
      - mpmath
      - munch
      - networkx
      - numpy
      - opencv-contrib-python
      - pkginfo
      - pointpats
      - psutil
      - pygments
      - pytest-faulthandler
      - readme-renderer
      - requests-toolbelt
      - rfc3986
      - rich
      - secretstorage
      - snowballstemmer
      - sphinx
      - sphinx-rtd-theme
      - sphinxcontrib-applehelp
      - sphinxcontrib-devhelp
      - sphinxcontrib-htmlhelp
      - sphinxcontrib-jsmath
      - sphinxcontrib-qthelp
      - sphinxcontrib-serializinghtml
      - sympy
      - twine
      - webencodings
      - zipp
