name: MGSurvE
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - asttokens
  - backcall
  - backports
  - backports.functools_lru_cache
  - black
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cartopy
  - click
  - cycler
  - dataclasses
  - deap
  - debugpy
  - decorator
  - entrypoints
  - executing
  - fonttools
  - freetype
  - fribidi
  - geos
  - giflib
  - ipython
  - jbig
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - keyutils
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libimagequant
  - liblapack
  - libnghttp2
  - libnsl
  - libopenblas
  - libpng
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libzlib
  - lz4-c
  - matplotlib-base
  - matplotlib-inline
  - munkres
  - mypy_extensions
  - ncurses
  - nest-asyncio
  - numpy
  - openjpeg
  - openssl
  - packaging
  - parso
  - pathspec
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - proj
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pygments
  - pyparsing
  - pyproj
  - pyshp
  - python
  - python-dateutil
  - python_abi
  - pyzmq
  - readline
  - scipy
  - shapely
  - six
  - sqlite
  - stack_data
  - tk
  - tomli
  - tornado
  - traitlets
  - typed-ast
  - typing_extensions
  - tzdata
  - unicodedata2
  - wcwidth
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
    - alabaster
    - appdirs
    - argon2-cffi
    - argon2-cffi-bindings
    - attrs
    - babel
    - beautifulsoup4
    - bleach
    - certifi
    - cffi
    - charset-normalizer
    - click-plugins
    - cligj
    - commonmark
    - compress-pickle
    - cryptography
    - defusedxml
    - dill
    - docutils
    - fiona
    - geopandas
    - haversine
    - idna
    - imagesize
    - importlib-metadata
    - iniconfig
    - ipykernel
    - ipython-genutils
    - ipywidgets
    - jeepney
    - jinja2
    - joblib
    - jsonschema
    - jupyter
    - jupyter-console
    - jupyter-core
    - jupyterlab-pygments
    - jupyterlab-widgets
    - keyring
    - libpysal
    - markupsafe
    - mgsurve
    - mistune
    - munch
    - nbclient
    - nbconvert
    - nbformat
    - networkx
    - notebook
    - opencv-contrib-python
    - pandas
    - pandocfilters
    - pkginfo
    - pluggy
    - pointpats
    - prometheus-client
    - prompt-toolkit
    - py
    - pycparser
    - pyrsistent
    - pytest
    - pytz
    - qtconsole
    - qtpy
    - readme-renderer
    - requests
    - requests-toolbelt
    - rfc3986
    - rich
    - scikit-learn
    - secretstorage
    - send2trash
    - setuptools
    - snowballstemmer
    - soupsieve
    - sphinx
    - sphinx-rtd-theme
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - terminado
    - testpath
    - threadpoolctl
    - twine
    - urllib3
    - vincenty
    - webencodings
    - widgetsnbextension
    - zipp
