name: MGSurvE
channels:
  - conda-forge
  - giuliorossetti
  - defaults
dependencies:
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cartopy
  - certifi
  - cycler
  - deap
  - fonttools
  - freetype
  - geos
  - giflib
  - jbig
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libssh2
  - libtiff
  - libwebp
  - libwebp-base
  - libxcb
  - libzlib
  - llvm-openmp
  - lz4-c
  - matplotlib-base
  - munkres
  - ncurses
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pillow
  - pip
  - proj
  - pthread-stubs
  - pyparsing
  - pyproj
  - pyshp
  - python
  - python-dateutil
  - python_abi
  - readline
  - scipy
  - setuptools
  - shapely
  - six
  - sqlite
  - tk
  - tzdata
  - unicodedata2
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zlib
  - zstd
  - pip:
    - alabaster
    - appdirs
    - appnope
    - argon2-cffi
    - argon2-cffi-bindings
    - asttokens
    - attrs
    - babel
    - backcall
    - beautifulsoup4
    - bleach
    - cffi
    - charset-normalizer
    - click
    - click-plugins
    - cligj
    - commonmark
    - compress-pickle
    - debugpy
    - decorator
    - defusedxml
    - dill
    - docutils
    - entrypoints
    - executing
    - fastjsonschema
    - fiona
    - geopandas
    - haversine
    - idna
    - imagesize
    - importlib-metadata
    - iniconfig
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - joblib
    - jsonschema
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyterlab-pygments
    - jupyterlab-widgets
    - keyring
    - libpysal
    - markupsafe
    - matplotlib-inline
    - mgsurve
    - mistune
    - munch
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - notebook
    - opencv-contrib-python
    - pandas
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - pkginfo
    - pluggy
    - pointpats
    - prometheus-client
    - prompt-toolkit
    - psutil
    - ptyprocess
    - pure-eval
    - py
    - pycparser
    - pygments
    - pyrsistent
    - pytest
    - pytz
    - pyzmq
    - qtconsole
    - qtpy
    - readme-renderer
    - requests
    - requests-toolbelt
    - rfc3986
    - rich
    - scikit-learn
    - send2trash
    - snowballstemmer
    - soupsieve
    - sphinx
    - sphinx-rtd-theme
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - stack-data
    - terminado
    - testpath
    - threadpoolctl
    - tomli
    - tornado
    - traitlets
    - twine
    - urllib3
    - vincenty
    - wcwidth
    - webencodings
    - widgetsnbextension
    - zipp
