name: PyTests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: '3.10'
          conda-channels: anaconda, conda-forge
          activate-conda: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make develop
          pip install pytest
          # conda install cartopy
      - name: Run tests with pytest
        run: |
          make test
